version: '3.8'

services:
    php-fpm:
        image: wordpress
        container_name: wordpress
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: user
                uid: 1000
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        networks:
            - app_network
        environment:
            - WORDPRESS_DB_HOST=host.docker.internal:3306
            - WORDPRESS_DB_NAME=loja_teste
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=password

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./.build/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app_network
        depends_on:
            - php-fpm

networks:
    app_network:
        driver: bridge
